external_components:
  - source:
      type: git
      url: https://github.com/bdraco/esphome-ratgdo
    refresh: 1s

ratgdo:
  id: ${id_prefix}

binary_sensor:
  - platform: ratgdo
    type: motion
    id: ${id_prefix}_motion
    ratgdo_id: ${id_prefix}
    name: "${friendly_name} Motion"
    device_class: motion
  - platform: ratgdo
    type: obstruction
    id: ${id_prefix}_obstruction
    ratgdo_id: ${id_prefix}
    name: "${friendly_name} Obstruction"
    device_class: problem

number:
  - platform: ratgdo
    id: ${id_prefix}_rolling_code_counter
    type: rolling_code_counter
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "${friendly_name} Rolling Code Counter"

cover:
  - platform: ratgdo
    id: ${id_prefix}_garage
    device_class: garage
    name: ${friendly_name}
    ratgdo_id: ${id_prefix}


light:
  - platform: ratgdo
    id: ratgdo_light
    name: "${friendly_name} Light"
    ratgdo_id: ${id_prefix}

uart:
  tx_pin: 
      number: 2
      inverted: true
  rx_pin:
      number: 4
      inverted: true
  baud_rate: 9600


button:
  - platform: restart
    name: "${friendly_name} Restart"

