---

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

substitutions:
  uart_tx_pin: D4
  uart_rx_pin: D2
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

