---
substitutions:
  id_prefix: ratgdov2
  friendly_name: "RATGDOv2"

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.0"

dashboard_import:
  package_import_url: github://esphome-ratgdo/esphome-ratgdo/ratgdo_v2board_esp8266_d1_mini.yaml@main

packages:
  # Git repo examples
  remote_package:
    url: https://github.com/esphome-ratgdo/esphome-ratgdo
    files: [base.yml, v2board_esp8266_d1_mini_include.yaml]
    refresh: 1s # optional

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

ota:

improv_serial:

wifi:
  ap:

logger:
